components:
  schemas:
    ModeloDeDados:
      description: Modelo de dados associado ao projeto BIOMA/siBIO
      properties:
        consumoEnergia:
          description: Consumo comulativo de energia elétrica em kWh
          minimum: 0
          type: number
          x-ngsi:
            type: Property
            units: kWh
        consumoAgua:
          description: Consumo comulativo de água em m^3
          minimum: 0
          type: number
          x-ngsi:
            type: Property
            units: m3
        id:
          anyOf:
          - description: 'Propriedade: Formato do identificador de qualquer entidade.'
            maxLength: 256
            minLength: 1
            pattern: ^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$
            type: string
          - description: 'Propriedade: Formato do identificador de qualquer entidade.'
            format: uri
            type: string
          description: 'Identificador único da entidade.'
          x-ngsi:
            type: Property
        type:
          description: 'Entidade tipo ModeloDeDados'
          enum:
            - ModeloDeDados
          type: string
      x-ngsi:
        type: Property
      required:
        - id
        - type
      type: object
      x-derived-from: ""
      x-disclaimer: 'jpcoelho @ BIOMA 2021'
      x-license-url: https://github.com/jpcoelhoATipbDOTpt/BIOMA/blob/main/LICENSE
      x-model-tags: ""
      x-version: 0.0.3
  
info:
  description: Modelo de dados base para o projeto BIOMA
  title: BIOMA Project
  version: 1.0.0
openapi: 3.0.0
paths:
  /BIOMA/siBIO/entities:
    get:
      responses:
        '200':
          description: OK
          content:
            application/ld+json:
              schema:
                type: object
